### ISSUE TITLE
memestra is missing fixes on pypi

### ISSUE THREAD

**Issue by racko** [QuantStack/memestra#65]
https://pypi.org/project/memestra/ offers [release/0.2.0](https://github.com/QuantStack/memestra/tree/release/0.2.0) as the "latest version", which users usually install by default, I assume. There https://github.com/QuantStack/memestra/commit/cde5ef6fb85f98b36efea6262bd6f38215778a12 (https://github.com/QuantStack/memestra/pull/59 / https://github.com/QuantStack/memestra/pull/60) is missing. As a result using memestra results in `PermissionError: [Errno 13] Permission denied: '/usr/share/memestra'`.

Edit: I see that https://github.com/QuantStack/memestra/commit/6165c6412c00be869ec6d6472efd7beec4a71480 would also be missing.

**Comment by serge-sans-paille** [comment]
Should be fixed by 0.2.1

**Comment by racko** [comment]
In can confirm that it does. Thank you! :slightly_smiling_face:
